export default {
    START_KARBONITE:100,
    START_FUEL:500,
    UNIT_FUEL_PRICE:50,
    CHURCH_KARBONITE_COST:50,
    PILGRIM_KARBONITE_COST:10,
    CRUSADER_KARBONITE_COST:20,
    PROPHET_KARBONITE_COST:25,
    PREACHER_KARBONITE_COST:30,
    BUILDING_VISION_RADIUS:10,
    UNPASSABLE_TERRAIN_VALUE:1000000,
    SYMMETRY_VERTICAL:1,
    SYMMETRY_HORIZONTAL:2
};